# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
