# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_profile_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.FloatField(),
        ),
    ]
